# Generated by Django 3.2.18 on 2023-02-27 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20230227_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='grand_total_price',
            new_name='grand_total',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_total_price',
            new_name='order_total',
        ),
    ]
